version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:5000"
    environment:
      - CATALOG_URL=http://catalog-service:5001/catalog
      - ORDER_URL=http://order-service:5002/order
    depends_on:
      - catalog-service
      - order-service

  catalog-service:
    build: ./catalog-service
    ports:
      - "5001:5001"
    volumes:
      - catalog-data:/app/catalog.db
    
  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    volumes:
      - orders-data:/app/orders.db
  
volumes:
  catalog-data:
  orders-data: