version: '3.8'

services:
  # Define the services for the application
  # Each service is a separate container
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpw
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql+psycopg2://authuser:authpw@postgres:5432/authdb
    volumes:
      - auth-data:/data
    ports:
      - "5003:5003"

  catalog-service:
    build: ./catalog-service
    environment:
      - DATABASE_URL=postgresql+psycopg2://authuser:authpw@postgres:5432/authdb
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    volumes:
      - catalog-data:/app/catalog.db
    
    
  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    environment:
      - CATALOG_HOST=catalog-service     # DNS name provided by Compose
      - CATALOG_PORT=5001
      - DATABASE_URL=postgresql+psycopg2://authuser:authpw@postgres:5432/authdb
    depends_on: [catalog-service]
    volumes:
      - orders-data:/data
    
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:5000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CATALOG_HOST=catalog-service
      - CATALOG_PORT=5001
      - ORDER_HOST=order-service
      - ORDER_PORT=5002
      - AUTH_HOST=auth-service
      - AUTH_PORT=5003
      - DATABASE_URL=postgresql+psycopg2://svc_user:svc_pass@postgres:5432/authdb
    depends_on:
      - catalog-service
      - order-service
      - auth-service

# Define the volumes for persistent data storage  
volumes:
  catalog-data:
  orders-data:
  auth-data:
  postgres-data: