version: '3.8'

services:
  # Define the services for the application
  # Each service is a separate container
  catalog-service:
    build: ./catalog-service
    ports:
      - "5001:5001"
    volumes:
      - catalog-data:/data
    environment:
      - DB_PATH=/data/catalog.db
    
  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    environment:
      - CATALOG_HOST=catalog-service     # DNS name provided by Compose
      - CATALOG_PORT=5001
      - DB_PATH=/data/orders.db
    depends_on: [catalog-service]
    volumes:
      - orders-data:/data
    
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:5000"
    environment:
      - CATALOG_HOST=catalog-service
      - CATALOG_PORT=5001
      - ORDER_HOST=order-service
      - ORDER_PORT=5002
    depends_on:
      - catalog-service
      - order-service

# Define the volumes for persistent data storage  
volumes:
  catalog-data:
  orders-data: